name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      # - name: Test
      #   run: dotnet test --no-restore --verbosity normal
      - name: List out directory contents
        run: echo "Listing the contents of the GitHub workspace directory"
      - name: work directory
        run: ls ${{ github.workspace }}
      - name: "Recursively listing all contents of the current directory"
        run: echo "Recursively listing all contents of the current directory"
      - name: work directory
        run: ls -R
